services:
  analysis-de:
    image: tobiaswaslowski/grammatical-analysis
    build:
      context: ../sidecars/morphology
      dockerfile: docker/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "8001:8000"
    environment:
      - SPACY_MODEL=de_core_news_sm
      - LANGUAGE_CODE=de
      - RABBITMQ_HOST=rabbitmq
      - EXCHANGE=morphological_analysis

  analysis-ru:
    image: tobiaswaslowski/grammatical-analysis
    build:
      context: ../sidecars/morphology
      dockerfile: docker/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "8002:8000"
    environment:
      - SPACY_MODEL=ru_core_news_sm
      - LANGUAGE_CODE=ru
      - RABBITMQ_HOST=rabbitmq
      - EXCHANGE=morphological_analysis

  inflection-ru:
    image: slowprog/pymorphy-api
    ports:
      - "8010:8000"

  postgresql:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grammr
    healthcheck:
      test: [ "CMD", "psql", "postgresql://user:password@localhost:5432/grammr", "-c", "select 1;" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf