services:
  analysis:
    image: tobiaswaslowski/grammatical-analysis
    build:
      context: ../sidecars/analysis
      dockerfile: docker/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    environment:
      - SPACY_MODEL=ru_core_news_sm
