services:
  analysis:
    image: tobiaswaslowski/grammatical-analysis
    build:
      context: ../sidecars/analysis
      dockerfile: docker/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    environment:
      - SPACY_MODELS=ru_core_news_sm,de_core_news_sm

  postgresql:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grammr
    healthcheck:
      test: [ "CMD", "psql", "postgresql://user:password@localhost:5432/grammr", "-c", "select 1;" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]
