{
 "title": "core",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "grammr-dev,grammr" }
  ]
 },
 "panels": [
  {
   "title": "Most recent logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", container_name=\"grammr\"} != \"health\" != \"prometheus\" | json | logfmt | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Unregistered Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_anonymous_user_count{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migrated users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "migrated_anonymous_user_count{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}