{
 "title": "Lambdas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "dev,prod" }
  ]
 },
 "panels": [
  {
   "title": "Morphology Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "grammr-tts-dev" },
     "expression": "SEARCH('{AWS/Lambda,FunctionName} FunctionName=~\"*-$env\" \"Duration\"', \"Maximum\", 300)",
     "metricEditorMode": 1,
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-central-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TTS Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "grammr-tts-dev" },
     "expression": "SEARCH('{AWS/Lambda,FunctionName} FunctionName=\"grammr-tts-$env\" MetricName=\"Duration\"', \"Maximum\", 300)",
     "metricEditorMode": 1,
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-central-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "SUM(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Errors\"', 'Sum'))",
     "metricEditorMode": 1,
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-central-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}