languages:
  - code: ru
    model: ru_core_news_lg
    morphology:
      enabled: true
      host: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-ru"
    inflection:
      enabled: true
      uri: "inflection-ru.grammr.svc.cluster.local"
  - code: de
    model: de_core_news_lg
    morphology:
      enabled: true
      host: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-de"
    inflection:
      enabled: false
  - code: en
    model: en_core_web_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-en"
    inflection:
      enabled: false
  - code: it
    model: it_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-it"
    inflection:
      enabled: true
      uri: "inflection-it.grammr.svc.cluster.local"
  - code: es
    model: es_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-es"
    inflection:
      enabled: true
      uri: "inflection-es.grammr.svc.cluster.local"
  - code: pt
    model: pt_core_news_md
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-pt"
    inflection:
      enabled: true
      uri: "inflection-pt.grammr.svc.cluster.local"
  - code: fr
    model: fr_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-fr"
    inflection:
      enabled: true
      uri: "http://inflection-fr.grammr.svc.cluster.local:8000/inflect"

multiInflection:
  languageCodes: ["it", "es", "pt", "fr"]

allowedOrigin: "https://grmmr.vercel.app"