languages:
  - code: ru
    model: ru_core_news_lg
    morphology:
      enabled: true
      host: "morphology-ru.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: true
      host: "inflection-ru.grammr.svc.cluster.local"
      port: 8000
      repository: tobiaswaslowski/grammr-inflection-ru
  - code: de
    model: de_core_news_lg
    morphology:
      enabled: true
      host: "morphology-de.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: false
  - code: en
    model: en_core_web_lg
    morphology:
      enabled: true
      host: "morphology-en.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: false
  - code: it
    model: it_core_news_lg
    morphology:
      enabled: true
      host: "morphology-it.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: true
      host: "inflection-it.grammr.svc.cluster.local"
      port: 8000
  - code: es
    model: es_core_news_lg
    morphology:
      enabled: true
      host: "morphology-es.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: true
      host: "inflection-es.grammr.svc.cluster.local"
      port: 8000
  - code: pt
    model: pt_core_news_md
    morphology:
      enabled: true
      host: "morphology-pt.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: true
      host: "inflection-pt.grammr.svc.cluster.local"
      port: 8000
  - code: fr
    model: fr_core_news_lg
    morphology:
      enabled: true
      host: "morphology-fr.grammr.svc.cluster.local"
      port: 8000
    inflection:
      enabled: true
      host: "inflection-fr.grammr.svc.cluster.local"
      port: 8000

multiInflection:
  languageCodes: ["it", "es", "pt", "fr"]

allowedOrigin: "https://grmmr.vercel.app"