version: '3'
tasks:
  start-env:
    desc: Start the local environment
    cmds:
      - docker compose -f local/docker-compose.yaml -p grammr up -d --remove-orphans --wait
      - task: setup-mockserver
      - task: setup-db

  stop-env:
    desc: Stop the local environment
    cmds:
      - docker compose -f local/docker-compose.yaml -p grammr down

  setup-mockserver:
    desc: Create mockserver expectations to mock OpenAI Responses API
    dir: local/expectations
    cmds:
      - python set_expectations.py

  setup-db:
    desc: Populate database with paradigms
    dir: local/data
    cmds:
      - psql 'postgresql://user:password@localhost:5432/grammr' -f data.sql

  unit-test:
    desc: Run unit tests
    cmds:
      - ./mvnw clean package test

  integration-test:
    desc: Run integration tests
    cmds:
      - task: start-env
      - ./mvnw clean package test -P integration

  test:
    desc: Run unit tests, start environment, and run integration tests
    cmds:
      - task: unit-test
      - task: integration-test

  start-frontend:
    desc: Run the Next.js frontend
    dir: frontend
    cmds:
      - pnpm run dev

  lint:
    desc: Run linter
    dir: frontend
    cmds:
      - pnpm lint:fix
      - pnpm lint:strict
      - pnpm run typecheck
      - pnpm build

  run:
    desc: Start environment and run the application with local profile
    env:
      SPRING_PROFILES_ACTIVE: local
    cmds:
      - task: start-env
      - ./mvnw spring-boot:run &
      - task: start-frontend
