server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: grammr
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"grammr\""
    open-in-view: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health

openai:
  api-key: ${OPENAI_API_KEY}
  completions:
    model: gpt-4o-mini
  transcription:
    model: whisper-1
    verbose: false

grammr:
  default:
    user:
      language_spoken: EN
      language_learned: DE

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}

analysis:
  rest:
    port: 8000
    endpoint: morphological-analysis
  messaging:
    exchange: morphological_analysis
    queue: core-morphological-analysis-complete
    routing-key:
      complete: morphological-analysis.complete
      requested: morphological-analysis.requested
