spring:
  cors:
    allowed-origin: "${ALLOWED_ORIGIN}"
  datasource:
    url: jdbc:${DATASOURCE_URL}
    username: grammr
    password: ${DATASOURCE_PASSWORD}

grammr:
  anki:
    api:
      host: ${ANKI_EXPORTER_URL}

clerk:
  jwt-key: '-----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvsWGcKsfmjJjiN9DnwK2
  K3mX5T2s6MhGFSVyXCON+xJRfrJPAGd3PYzSPLK6jgWus/7YX3vS5AQ0PCWeRnY0
  60UXvYwG4H+ayanuqHO14MwTOwZx1LzdqOf24M2u+f94hI+DTk6LT2fOZN+pAiBn
  RLif4ac+5MVkzl2oWCMw5fFxhrJfZ8Hz7AxP1MxRmkurO4w/pUWoeDxYys3txySH
  VFEEen38awkq9yLleywb+rG5I/jEWgE/I/qr/U7fYAdQK3rGM51wfqUOsuaND8Ui
  cnXGsy4uPH038gqQWngClnhUO8TKM0I1gf2I0B9zoKtHuCONNnWtnqrwnHyNOjfI
  FwIDAQAB
  -----END PUBLIC KEY-----'
  authorized-party: 'https://dev.grammr.app'
