server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false
  compression:
    enabled: false

spring:
  application:
    name: grammr
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"grammr\""
    open-in-view: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}
  completions:
    model: gpt-4o-mini
  transcription:
    model: whisper-1
    verbose: false

clerk:
  jwt-key: ${CLERK_SECRET_KEY}

grammr:
  anki:
    api:
      host: http://localhost:8030
      endpoint: /create
  languages:
    mount-path: /app/config/languages.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
