server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: grammr
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"grammr\""
    open-in-view: false
  security:
    hashing:
      pepper: ${PEPPER_SECRET}
    encryption:
      key: ${ENCRYPTION_KEY}
      salt: ${ENCRYPTION_SALT}
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

openai:
  api-key: ${OPENAI_API_KEY}
  completions:
    model: gpt-4o-mini
  transcription:
    model: whisper-1
    verbose: false
  tts:
    model: tts-1
    voice: nova

grammr:
  anki:
    api:
      host: http://localhost:8030
      endpoint: /create
  default:
    user:
      language-spoken: EN
      language-learned: DE
  languages:
    mount-path: /app/config/languages.yml
