spring:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN}
  datasource:
    url: ${DATASOURCE_URL}

grammr:
  anki:
    api:
      host: ${ANKI_EXPORTER_URL}

clerk:
  jwt-key: ${JWT_PUBLIC_KEY}
  authorized-party: ${ALLOWED_ORIGIN}
