server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false
  compression:
    enabled: false

spring:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN}
  application:
    name: grammr
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: grammr
    open-in-view: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
  flyway:
    default-schema: grammr

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}
  completions:
    model: gpt-4o-mini

clerk:
  jwt-key: ${CLERK_SECRET_KEY}
  authorized-party: ${ALLOWED_ORIGIN}

grammr:
  anki:
    api:
      host: ${ANKI_EXPORTER_URL}
      endpoint: /create
  languages:
    mount-path: /app/config/languages.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
