spring:
  cors:
    allowed-origin: "http://localhost:3000"
  security:
    hashing:
      pepper: pepper
    encryption:
      key: some-key
      salt: c0ffee
  datasource:
    url: jdbc:postgresql://localhost:5432/grammr?currentSchema=grammr
    username: user
    password: password

grammr:
  languages:
    mount-path: src/test/resources/languages.yml