spring:
  cors:
    allowed-origin: "${ALLOWED_ORIGIN}"
  datasource:
    url: jdbc:postgresql://postgres.grammr.svc.cluster.local:5432/grammr?currentSchema=grammr
    username: grammr
    password: ${DATASOURCE_PASSWORD}

grammr:
  anki:
    api:
      host: http://anki-exporter.grammr.svc.cluster.local:8000