server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: grammr
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"grammr\""
    open-in-view: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health

openai:
  api-key: ${OPENAI_API_KEY}
  completions:
    model: gpt-4o-mini
  transcription:
    model: whisper-1
    verbose: false

grammr:
  default:
    user:
      language_spoken: EN
      language_learned: DE

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}

analysis:
  rest:
    base-url: ${ANALYSIS_ENDPOINT}