spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grammr?currentSchema=grammr
    username: user
    password: password

grammr:
  languages:
    mount-path: src/test/resources/languages.yml