server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: grammr

management:
  endpoints:
    web:
      exposure:
        include: health

llm:
  openai:
    api-key: ${OPENAI_API_KEY}
    default-model: gpt-4o-mini

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}