environment: prod
allowedOrigin: "https://grammr.app"
fullnameOverride: "core"

environmentVariables:
  - name: DATASOURCE_URL
    value: "jdbc:postgresql://postgres.grammr.svc.cluster.local:5432/grammr?currentSchema=grammr"
  - name: ALLOWED_ORIGIN
    value: "https://grammr.app"
  - name: ANKI_EXPORTER_URL
    value: "http://anki-exporter.grammr.svc.cluster.local:8000"
  - name: SPRING_PROFILES_ACTIVE
    value: prod

ingress:
  enabled: true
  className: "cloudflare-tunnel"
  host: server-prod.grammr.app
    - /api/
    - /actuator/health

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5

languages:
  - code: ru
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-ru"
    inflection:
      enabled: true
      uri: "http://inflection-ru.grammr.svc.cluster.local:8000/inflect"
  - code: de
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-de"
    inflection:
      enabled: false
  - code: en
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-en"
    inflection:
      enabled: false
  - code: it
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-it"
    inflection:
      enabled: true
      uri: "http://inflection-it.grammr.svc.cluster.local:8000/inflect"
  - code: es
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-es"
    inflection:
      enabled: true
      uri: "http://inflection-es.grammr.svc.cluster.local:8000/inflect"
  - code: pt
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-pt"
    inflection:
      enabled: true
      uri: "http://inflection-pt.grammr.svc.cluster.local:8000/inflect"
  - code: fr
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/prod/morphology-fr"
    inflection:
      enabled: true
      uri: "http://inflection-fr.grammr.svc.cluster.local:8000/inflect"
