environment: dev
fullnameOverride: "core"

environmentVariables:
  - name: DATASOURCE_URL
    value: "jdbc:postgresql://postgres.grammr-dev.svc.cluster.local:5432/grammr?currentSchema=grammr"
  - name: ALLOWED_ORIGIN
    value: "https://dev.grammr.app"
  - name: ANKI_EXPORTER_URL
    value: "http://anki-exporter.grammr-dev.svc.cluster.local:8000"
  - name: SPRING_PROFILES_ACTIVE
    value: dev

ingress:
  enabled: true
  className: "cloudflare-tunnel"
  host: server-dev.grammr.app
  paths:
    - /api/
    - /actuator/health

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5

languages:
  - code: ru
    morphology:
      enabled: true
      uri: "https://b4l7c733qf.execute-api.eu-central-1.amazonaws.com/dev/morphology-ru"
    inflection:
      enabled: true
      uri: "http://inflection-ru.grammr-dev.svc.cluster.local:8000/inflect"
  - code: de
    morphology:
      enabled: true
      uri: "https://b4l7c733qf.execute-api.eu-central-1.amazonaws.com/dev/morphology-de"
    inflection:
      enabled: false
  - code: en
    morphology:
      enabled: true
      uri: "https://b4l7c733qf.execute-api.eu-central-1.amazonaws.com/dev/morphology-en"
    inflection:
      enabled: false
  - code: es
    morphology:
      enabled: true
      uri: "https://b4l7c733qf.execute-api.eu-central-1.amazonaws.com/dev/morphology-es"
    inflection:
      enabled: true
      uri: "http://inflection-es.grammr-dev.svc.cluster.local:8000/inflect"

