{{- range .Values.languages }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .languageCode }}-grammr-morphology
  labels:
    app: {{ .languageCode }}-grammr-morphology
    language: {{ .languageCode }}
spec:
  selector:
    app: {{ .languageCode }}-grammr-morphology
    language: {{ .languageCode }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
{{- end }}