{{- range .Values.languages }}
{{- if .inflection.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .code }}-inflection
  labels:
    app: {{.code }}-inflection
    language: {{ .code }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .code }}-inflection
      language: {{ .code }}
  template:
    metadata:
      labels:
        app: {{ .code}}-inflection
        language: {{ .code }}
    spec:
      containers:
        - name: {{ .code}}-inflection
          image: "{{ .inflection.repository }}:{{ $.Values.image.tag }}"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .inflection.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .inflection.port }}
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
{{- end }}
{{- end }}