apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  openai_api_key: {{ .Values.openai_api_key | b64enc }}
  telegram_token: {{ .Values.telegram_token | b64enc }}
  datasource_password: {{ .Values.datasource_password | b64enc }}
