apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  openai_api_key: {{ .Values.openai_api_key | b64enc }}
  pepper: {{ include "utils.secret.keepOrCreate" (dict "namespace" .Release.Namespace "name" "grammr-core-auth" "key" "pepper") }}
  observability_password: {{ include "utils.secret.keepOrCreate" (dict "namespace" .Release.Namespace "name" "grammr-core-auth" "key" "observability_password") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-encryption
data:
    encryption_key: {{ include "utils.secret.keepOrCreate" (dict "namespace" .Release.Namespace "name" "grammr-core-encryption" "key" "encryption_key") }}
    salt: {{ include "utils.secret.keepOrCreateHex" (dict "namespace" .Release.Namespace "name" "grammr-core-encryption" "key" "salt") }}