apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingolift-core.fullname" . }}
  labels:
    {{- include "lingolift-core.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lingolift-core.selectorLabels" . | nindent 4 }}
