export enum PartOfSpeechTag {
  ADJ = 'Adjective',
  PROPN = 'Proper Noun',
  NOUN = 'Noun',
  VERB = 'Verb',
  ADV = 'Adverb',
  INTJ = 'Interjection',
  ADP = 'Adposition',
  AUX = 'Auxiliary Verb',
  CCONJ = 'Coordinating Conjunction',
  DET = 'Determiner',
  NUM = 'Numeral',
  PART = 'Particle',
  PRON = 'Pronoun',
  SCONJ = 'Subordinating Conjunction',
  PUNCT = 'Punctuation',
  SYM = 'Symbol',
  X = 'Other',
}
