name: Build anki-exporter image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'microservice/anki-exporter/**'
      - '.github/workflows/build_service.yml'
      - '.github/workflows/build_anki_exporter.yaml'

jobs:
  build:
    uses: ./.github/workflows/build_service.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./microservice/anki-exporter"
      image_name: "grammrapp/anki-exporter"
