name: Build anki-exporter sidecar
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sidecars/anki-exporter/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_anki.yaml'

jobs:
  build-anki-exporter-sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/anki-exporter"
      image_name: "tobiaswaslowski/grammr-anki-exporter"
