name: Build multi-languge inflections sidecar

on:
  push:
    branches: [ main ]
    paths:
      - 'sidecars/multi-inflection/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/build_multi_inflection.yaml'

jobs:
  build-multi-inflection-sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/multi-inflection"
      image_name: "tobiaswaslowski/grammr-multi-inflection"
