name: Build AWS Lambda Docker images

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
    paths:
      - 'config.yaml'
      - 'sidecars/morphology/**'
      - '.github/workflows/deploy_morphology_serverless.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Derive and store version
        id: version
        run: |
          echo "version=$(cd ./sidecars/morphology && poetry version -s)" >> $GITHUB_OUTPUT

      - name: Parse YAML and create build matrix
        id: set-matrix
        run: |
          # pip install pyyaml
          # export MATRIX=$(python ./sidecars/morphology/docker/image_generation_helper.py)
          # echo "Generated matrix for building images: $MATRIX"
          # echo "matrix=$MATRIX" | tee -a "$GITHUB_OUTPUT"
          echo "matrix={\"include\":[{\"code\":\"ru\",\"model\":\"ru_core_news_md\"},{\"code\":\"de\",\"model\":\"de_core_news_sm\"},{\"code\":\"en\",\"model\":\"en_core_web_sm\"},{\"code\":\"it\",\"model\":\"it_core_news_md\"},{\"code\":\"es\",\"model\":\"es_core_news_sm\"},{\"code\":\"pt\",\"model\":\"pt_core_news_md\"},{\"code\":\"fr\",\"model\":\"fr_core_news_sm\"}]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - code: "ru"
            model: "ru_core_news_lg"
          - code: "de"
            model: "de_core_news_lg"
          - code: "en"
            model: "en_core_web_lg"
          - code: "it"
            model: "it_core_news_lg"
          - code: "es"
            model: "es_core_news_lg"
          - code: "pt"
            model: "pt_core_news_lg"
          - code: "fr"
            model: "fr_core_news_lg"
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # required for ECR, see: https://github.com/serverless/serverless/issues/12808
          provenance: false
          context: sidecars/morphology/
          file: sidecars/morphology/docker/lambda.Dockerfile
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: 246770851643.dkr.ecr.eu-central-1.amazonaws.com/morphology:${{ needs.prepare.outputs.version }}-${{ matrix.code }}
          build-args: |
            SPACY_MODEL=${{ matrix.model }}

  deploy:
    needs: [ prepare, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Deploy Terraform
        working-directory: terraform
        env:
          TF_VAR_morphology_image_version: ${{ needs.prepare.outputs.version }}
        run: |
          terraform init -backend-config=config/dev.hcl
          terraform apply -auto-approve