name: Build russian inflections sidecar
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/inflection-ru/**'
      - 'sidecars/inflection-ru/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_inflection_ru.yaml'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      sidecar_changed: ${{ steps.filter.outputs.sidecar_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            sidecar_changed:
              - 'sidecars/inflection-ru/**'

  build_ru_inflection_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    if: ${{ needs.check_changes.outputs.sidecar_changed == 'true' }}
    needs: check_changes
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/inflection-ru"
      image_name: "tobiaswaslowski/grammr-inflection-ru"
