name: Build and deploy multi-languge inflections
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/multi-inflection/**'
      - 'sidecars/multi-inflection/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_multi_inflection.yaml'

jobs:
  build_multi_inflection_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/multi-inflection"
      image_name: "tobiaswaslowski/grammr-multi-inflection"

  deploy:
    runs-on: self-hosted
    needs:
      - build_multi_inflection_sidecar
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            --values ./charts/values/grammr.values.yaml \
            multi-inflection ./charts/multi-inflection
        
