name: Build and deploy Core
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
      - charts/grammr/**
      - environments/*/core.values.yaml
      - pom.xml
      - Dockerfile
      - .github/workflows/deploy_core.yml

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: maven

      - name: Unit tests
        run: ./lifecycle/qa.sh

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: grammr-core-jar
          path: target/grammr-core-1.0-SNAPSHOT.jar

  build_grammr_core:
    runs-on: ubuntu-latest
    needs: compile_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download jar
        uses: actions/download-artifact@v4
        with:
          name: grammr-core-jar
          path: target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: tobiaswaslowski/grammr-core
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev:
    runs-on: self-hosted
    needs: [ build_grammr_core ]
    environment: dev
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Postgres
        run: |
          helm upgrade --install \
            --values ./environments/dev/postgres.values.yaml \
            --namespace grammr-dev --create-namespace \
            --wait --timeout 600s \
            postgres oci://registry-1.docker.io/bitnamicharts/postgresql

      - name: Deploy core
        run: |
          export TAG="sha-$(git rev-parse --short HEAD)"
          helm upgrade --install \
            --set openai_api_key="$OPENAI_API_KEY" \
            --set image.tag="$TAG" \
            --values environments/dev/core.values.yaml \
            --namespace grammr-dev --create-namespace \
            --wait --timeout 600s \
            grammr-core ./charts/grammr

  deploy-prod:
    runs-on: self-hosted
    needs: [ deploy-dev ]
    environment: prod
    if: github.ref == 'refs/heads/main'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Postgres
        run: |
          helm upgrade --install \
            --values ./environments/prod/postgres.values.yaml \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            postgres oci://registry-1.docker.io/bitnamicharts/postgresql

      - name: Deploy core
        run: |
          export TAG="sha-$(git rev-parse --short HEAD)"
          helm upgrade --install \
            --set openai_api_key="$OPENAI_API_KEY" \
            --set image.tag="$TAG" \
            --values environments/prod/core.values.yaml \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            grammr-core ./charts/grammr
