name: Build and deploy morphology
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/morphology/**'
      - 'config.yaml'
      - 'sidecars/morphology/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_morphology.yaml'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      sidecar_changed: ${{ steps.filter.outputs.sidecar_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            sidecar_changed:
              - 'sidecars/morphology/**'

  build_morphology_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    if: ${{ needs.check_changes.outputs.sidecar_changed == 'true' }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/morphology"
      image_name: "tobiaswaslowski/grammr-morphology"

  deploy:
    runs-on: self-hosted
    needs:
      - build_morphology_sidecar
      - check_changes
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install --namespace grammr \
            --values config.yaml --wait --timeout 600s \
            morphology ./charts/morphology
        
