name: Deploy multi-languge inflection image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/morphology/**'
      - 'sidecars/morphology/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_morphology.yaml'

jobs:
  build_morphology_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/morphology"
      image_name: "tobiaswaslowski/grammr-morphology"

  deploy:
    runs-on: self-hosted
    needs:
      - build_morphology_sidecar
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install \
            --namespace grammr --create-namespace \ 
            --values ./charts/values/prod.morphology.values.yaml \
            --wait --timeout 600s \
            morphology ./charts/morphology
        
