name: Deploy multi-languge inflection image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/inflection-ru/**'
      - 'sidecars/inflection-ru/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_multi_inflection.yaml'

jobs:
  build_multi_inflection_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/inflection-ru"
      image_name: "tobiaswaslowski/grammr-inflection-ru"

  deploy:
    runs-on: self-hosted
    needs:
      - build_multi_inflection_sidecar
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            inflection-ru ./charts/inflection-ru
        
