name: Deploy Core to Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_grammr_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: maven

      - name: Build jar
        run: ./mvnw package -DskipTests=false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: tobiaswaslowski/grammr-core
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-prod:
    runs-on: self-hosted
    needs: [ build_grammr_core ]
    environment: prod
    concurrency: deploy-prod
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy core
        run: |
          export TAG="${GITHUB_REF#refs/tags/}"
          helm upgrade --install \
            --set openai_api_key="$OPENAI_API_KEY" \
            --set image.tag="$TAG" \
            --values environments/prod/core.values.yaml \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            grammr-core ./charts/grammr

