name: Build and deploy multi-languge inflections
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'environments/*/core.values.yaml'
      - 'charts/multi-inflection/**'
      - 'sidecars/multi-inflection/**'
      - '.github/workflows/build_sidecar.yml'
      - '.github/workflows/deploy_multi_inflection.yaml'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      sidecar_changed: ${{ steps.filter.outputs.sidecar_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            sidecar_changed:
              - 'sidecars/multi-inflection/**'

  build_multi_inflection_sidecar:
    uses: ./.github/workflows/build_sidecar.yml
    if: ${{ needs.check_changes.outputs.sidecar_changed == 'true' }}
    needs: check_changes
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      directory: "./sidecars/multi-inflection"
      image_name: "tobiaswaslowski/grammr-multi-inflection"

  deploy-dev:
    environment: dev
    runs-on: self-hosted
    needs:
      - build_multi_inflection_sidecar
      - check_changes
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install \
            --namespace grammr-dev --create-namespace \
            --wait --timeout 600s \
            --values ./environments/dev/core.values.yaml \
            multi-inflection ./charts/multi-inflection

  deploy-prod:
    environment: prod
    runs-on: self-hosted
    needs: [ deploy-dev ]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        run: |
          helm upgrade --install \
            --namespace grammr --create-namespace \
            --wait --timeout 600s \
            --values ./environments/prod/core.values.yaml \
            multi-inflection ./charts/multi-inflection
        
