name: Run Core tests
on:
  pull_request:
    branches-ignore:
      - 'release-please-**'

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: maven

      - name: Unit tests
        run: ./lifecycle/unit-test.sh

      - name: Integration tests
        run: ./lifecycle/integration-test.sh
