name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'Helm revision to rollback to (optional, defaults to previous revision)'
        required: false
        default: ''
      namespace:
        description: 'Kubernetes namespace for the Helm release (optional, defaults to grammr-dev)'
        required: false
        default: 'grammr-dev'
      release:
        description: 'Helm release name (optional, defaults to grammr-core)'
        required: false
        default: 'grammr-core'

jobs:
  rollback:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rollback grammr-core Helm release
        env:
          REVISION: ${{ github.event.inputs.revision }}
        run: |
          set -e
          RELEASE=${{ github.event.inputs.release }}
          NAMESPACE=${{ github.event.inputs.namespace }}

          if [ -z "$REVISION" ]; then
            # Get the previous revision
            REVISION=$(helm history $RELEASE -n $NAMESPACE --max=2 | awk 'NR==3{print $1}')
            if [ -z "$REVISION" ]; then
              echo "Could not determine previous revision."
              exit 1
            fi
          fi
          echo "Rolling back $RELEASE in $NAMESPACE to revision $REVISION"
          helm rollback $RELEASE $REVISION -n $NAMESPACE --wait

