name: Publish Swagger UI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build and run Spring Boot app
        run: |
          ./mvnw clean package -DskipTests
          mvn spring-boot:start -Dspring-boot.run.profiles=local

      - name: Fetch OpenAPI spec
        run: |
          curl http://localhost:8080/v3/api-docs > openapi.json

      - name: Kill Spring Boot app
        run: |
          mvn spring-boot:stop

      - name: Generate Swagger UI
        run: |
          mkdir swagger-ui
          curl -L https://github.com/swagger-api/swagger-ui/archive/refs/heads/master.zip -o swagger-ui.zip
          unzip swagger-ui.zip
          mv swagger-ui-master/dist/* swagger-ui/
          cp openapi.json swagger-ui/
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.json|g' swagger-ui/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui
