languages:
  - code: ru
    model: ru_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-ru"
    inflection:
      enabled: true
      uri: "http://inflection-ru.grammr-dev.svc.cluster.local:8000/inflect"
  - code: de
    model: de_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-de"
    inflection:
      enabled: false
  - code: en
    model: en_core_web_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-en"
    inflection:
      enabled: false
  - code: es
    model: es_core_news_lg
    morphology:
      enabled: true
      uri: "https://xqybdr4e07.execute-api.eu-central-1.amazonaws.com/dev/morphology-es"
    inflection:
      enabled: true
      uri: "http://inflection-es.grammr-dev.svc.cluster.local:8000/inflect"

multiInflection:
  languageCodes: ["es"]

allowedOrigin: "https://grmmr.vercel.app"
environment: dev