architecture: standalone

auth:
  username: grammr
  database: grammr
nameOverride: "postgres"

service:
  port: 5432

primary:
  resourcesPreset: nano
  nodeSelector:
    "kubernetes.io/hostname": rpi-master

persistence:
  primary:
    size: 2Gi
